spring:
  application:
    name: townmission-api
  profiles:
    active: local
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /app
    encoding:
      charset: UTF-8
      enabled: true
  port: 9090

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      minimum-idle: 50
      maximum-pool-size: 50

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

resources:
  root: file:/etc/secret/local
  driver-class: com.mysql.cj.jdbc.Driver
  path:
    endpoint: /ENDPOINT
    username: /USERNAME
    password: /PASSWORD
    redis-endpoint: /REDIS_ENDPOINT